### ISSUE TITLE
WebSocket connection failed: Unknown reason

### ISSUE THREAD

**Issue by tammersaleh** [reveal/multiplex#1]
When I try to test this plugin using the demo WebSocket server at https://reveal-js-multiplex-ccjbegmaii.now.sh/token, I get a `WebSocket connection to 'wss://reveal-js-multiplex-ccjbegmaii.now.sh/socket.io/?EIO=3&transport=websocket&sid=zaN_EvhrIjihGrDOCfvj' failed: Unknown reason` error:

<img width="1011" alt=" 2020-06-15 11-48-26" src="https://user-images.githubusercontent.com/2016/84694505-2857f280-aefe-11ea-9bc5-c8f738515397.png">

I've downloaded multiplex locally and am using it like such: 

``` html
    <script src="//cdnjs.cloudflare.com/ajax/libs/socket.io/2.2.0/socket.io.js"></script>
    <script src="assets/reveal.js-4.0.2/dist/reveal.js"></script>
    <script>
      Reveal.initialize({
        plugins: [ RevealMarkdown, RevealHighlight, RevealNotes ],
        multiplex: {
          secret: '15922463425415769872',
          id: 'aba4830d9748420c', // Obtained from socket.io server
          url: 'https://reveal-js-multiplex-ccjbegmaii.now.sh' // Location of socket.io server
        }
      });
    </script>
    <script src="assets/multiplex/master.js"></script>
  </body>
</html>
```

I got the `secret` and `id` values from https://reveal-js-multiplex-ccjbegmaii.now.sh/token#

I have no experience with WebSockets (or Zeit, and very little with Javascript, for that matter).  Any tips on debugging this would be greatly apprecaited.

**Comment by michaelmior** [comment]
Now the deployment referenced here (and in the README) is no longer available at all.

**Comment by hakimel** [comment]
We've deployed a new demo server, see https://github.com/reveal/multiplex/issues/2#issuecomment-683667435
