### ISSUE TITLE
Demo site is down.

### ISSUE THREAD

**Issue by DatStorm** [reveal/multiplex#2]
Hey 

The demo [site](https://reveal-js-multiplex-ccjbegmaii.now.sh/ ) is down for good. You need to move the code. Would love to have it fixed so I can get my token/id.

**Comment by hakimel** [comment]
I've put a new demo multiplex server on glitch and updated the readme. If you switch from `https://reveal-js-multiplex-ccjbegmaii.now.sh/` to `https://reveal-multiplex.glitch.me/` it should work.

I'm not sure what the hosting limits are on glitch but will keep an eye on it in case we need to move elsewhere.

**Comment by DatStorm** [comment]
Sounds awesome thank you!
