### ISSUE TITLE
File master.js silently renamed, documentation needs update

### ISSUE THREAD

**Issue by lechten** [reveal/multiplex#39]
In https://github.com/reveal/multiplex/commit/e8eb249129a195ae4ff3e4d6c3a0d7324ee5edfd the file `master.js` was silently renamed to `controller.js`, which is a backward incompatible change. 

The README still mentions `master.js`.

**Comment by hakimel** [comment]
Thanks for reporting. I missed that rename in the diff and have change it back again so that the documentation is still accurate.
